import type { BugKind, Severity } from '../types.js';

export type DetectorStatus = 'wired' | 'deferred' | 'dead';

export type DetectorInputSource = 'production' | 'synthetic-only' | 'unknown';

export type DetectorRegistryEntry = {
  kind: BugKind;
  status: DetectorStatus;
  /**
   * file:line where the BugDetection literal `kind: '<kind>'` is constructed.
   * For `status: 'wired'` this is the canonical detector site.
   * For `status: 'deferred' | 'dead'` this is undefined.
   */
  detectorSite?: string;
  /**
   * file:line where the runner that supplies input to the detector lives.
   * Same as detectorSite when the detector is also the runner (e.g. the
   * pen-test runner emits its own detections inline). Undefined for static
   * analysis kinds where no runtime runner is involved.
   */
  runnerSite?: string;
  /**
   * Whether the input is observed during a real navigation/test
   * (`production`) or synthesised by an explicit probe (`synthetic-only`).
   * Static analysis kinds are `production` (source files are real input).
   */
  inputSource: DetectorInputSource;
  /** Spec file the kind was promised by, e.g. 'SPEC_V05_SECURITY_HYGIENE.md'. */
  specReference: string;
  /**
   * Human-readable note. Required for non-'wired' entries to explain why.
   */
  note?: string;
  /** v0.29: per-kind severity default used when no detection-level severity is set. */
  defaultSeverity?: Severity;
  /**
   * V56: true once a DetectorContract entry exists for this kind.
   * Lockstep test enforces 1:1 between harness:true rows and DETECTOR_CONTRACTS entries.
   * Optional during the V56.1–V56.5 migration window; required for all wired kinds at V56.6.
   */
  harness?: boolean;
};

export const DETECTOR_REGISTRY: readonly DetectorRegistryEntry[] = [
  // — § Core (always wired) —
  {
    kind: 'console_error',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/console.ts:24',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'react_error',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/react.ts:45',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'critical',
  },
  {
    kind: 'hydration_mismatch',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/react.ts:38',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'network_5xx',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/network.ts:17',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'network_4xx_unexpected',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/network.ts:44',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'minor',
  },
  {
    kind: '404_for_linked_route',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/network.ts:55',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'missing_state_change',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/state-change.ts:27',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'unhandled_exception',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/console.ts:22',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'critical',
  },
  {
    kind: 'accessibility_critical',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/accessibility.ts:36',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'critical',
  },
  {
    kind: 'dom_error_text',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/dom-error-text.ts:28',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'surface_call_failed',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/execute.ts:925',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'visual_anomaly',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/vision.ts:411',
    runnerSite: 'packages/cli/src/phases/discover.ts',
    inputSource: 'production',
    specReference: 'SPEC.md',
    defaultSeverity: 'major',
  },
  // — § v0.5 security / hygiene (wired) —
  {
    kind: 'missing_csp_header',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/header-probe.ts:86',
    runnerSite: 'packages/cli/src/security/header-probe.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
    harness: true,
  },
  {
    kind: 'permissive_cors',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/header-probe.ts:121',
    runnerSite: 'packages/cli/src/security/header-probe.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'cookie_security_flags',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/header-probe.ts:152',
    runnerSite: 'packages/cli/src/security/header-probe.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'open_redirect',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/header-probe.ts:261',
    runnerSite: 'packages/cli/src/security/header-probe.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'sensitive_data_in_url',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/header-probe.ts:231',
    runnerSite: 'packages/cli/src/security/header-probe.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
    harness: true,
  },
  {
    kind: 'stack_trace_leak_in_response',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/header-probe.ts:205',
    runnerSite: 'packages/cli/src/security/header-probe.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'vulnerable_dependency_high',
    status: 'wired',
    detectorSite: 'packages/cli/src/static/tools/npm-audit.ts:31',
    inputSource: 'production',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'hardcoded_credentials_in_source',
    status: 'wired',
    detectorSite: 'packages/cli/src/static/tools/gitleaks.ts:30',
    inputSource: 'production',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'swallowed_error_empty_catch',
    status: 'wired',
    detectorSite: 'packages/cli/src/static/tools/eslint-no-empty.ts:36',
    inputSource: 'production',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'idor_horizontal',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/cross-user.ts:164',
    runnerSite: 'packages/cli/src/phases/cross-user.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'idor_vertical_role_escalate',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/cross-user.ts:244',
    runnerSite: 'packages/cli/src/phases/cross-user.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'critical',
  },
  // — § v0.21 IDOR rewire kinds (wired) —
  {
    kind: 'idor_horizontal_read',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/cross-user.ts:348',
    runnerSite: 'packages/cli/src/phases/cross-user.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V21_IDOR.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'idor_horizontal_mutate',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/cross-user.ts:345',
    runnerSite: 'packages/cli/src/phases/cross-user.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V21_IDOR.md',
    defaultSeverity: 'critical',
  },
  {
    kind: 'idor_vertical_suspicious',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/cross-user.ts:271',
    runnerSite: 'packages/cli/src/phases/cross-user.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V21_IDOR.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'auth_bypass_via_unauthed_route',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/cross-user.ts:328',
    runnerSite: 'packages/cli/src/phases/cross-user.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'no_rate_limit_on_login',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/auth-probes.ts:75',
    runnerSite: 'packages/cli/src/security/auth-probes.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V05_SECURITY_HYGIENE.md',
    defaultSeverity: 'major',
  },
  // — § v0.25 wired (promoted from deferred) —
  {
    kind: 'csrf_missing_on_mutating_route',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/csrf-detector.ts:73',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V25_DETECTOR_LESS_KINDS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'hallucinated_route',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/hallucinated-route.ts:78',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V25_DETECTOR_LESS_KINDS.md',
    defaultSeverity: 'major',
  },
  // — § v0.19 race-condition kinds (wired) —
  {
    kind: 'race_condition_double_submit',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/race-detectors.ts:74',
    runnerSite: 'packages/cli/src/phases/race-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V19_RACE_CONDITIONS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'race_condition_click_navigate',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/race-detectors.ts:114',
    runnerSite: 'packages/cli/src/phases/race-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V19_RACE_CONDITIONS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'race_condition_optimistic_revert',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/race-detectors.ts:198',
    runnerSite: 'packages/cli/src/phases/race-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V19_RACE_CONDITIONS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'race_condition_interleaved_mutations',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/race-detectors.ts:264',
    runnerSite: 'packages/cli/src/phases/race-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V19_RACE_CONDITIONS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'race_condition_cross_tab',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/race-detectors.ts:316',
    runnerSite: 'packages/cli/src/phases/race-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V19_RACE_CONDITIONS.md',
    defaultSeverity: 'major',
  },
  // — § v0.23 clock-injection kinds (deferred — clock-test-runner is a structural no-op without JWT issuance) —
  {
    kind: 'clock_skew_token_invalid',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V23_TIME_CLOCK.md',
    defaultSeverity: 'major',
    note: 'Deferred: clock-test-runner only emits when auth-token issuance is observed; all active fixtures use auth.kind=none so the runner is a structural no-op. Prerequisite: surface that issues JWTs with exp claims. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'clock_overflow',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V23_TIME_CLOCK.md',
    defaultSeverity: 'major',
    note: 'Deferred: clock-test-runner only emits when auth-token issuance is observed; all active fixtures use auth.kind=none so the runner is a structural no-op. Prerequisite: surface that issues JWTs with exp claims. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'clock_dst_corruption',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V23_TIME_CLOCK.md',
    defaultSeverity: 'minor',
    note: 'Deferred: clock-test-runner only emits when auth-token issuance is observed; all active fixtures use auth.kind=none so the runner is a structural no-op. Prerequisite: surface that issues JWTs with exp claims. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'clock_leap_day_failure',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V23_TIME_CLOCK.md',
    defaultSeverity: 'minor',
    note: 'Deferred: clock-test-runner only emits when auth-token issuance is observed; all active fixtures use auth.kind=none so the runner is a structural no-op. Prerequisite: surface that issues JWTs with exp claims. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'clock_timezone_display',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V23_TIME_CLOCK.md',
    defaultSeverity: 'minor',
    note: 'Deferred: clock-test-runner only emits when auth-token issuance is observed; all active fixtures use auth.kind=none so the runner is a structural no-op. Prerequisite: surface that issues JWTs with exp claims. See SWEEP_AUDIT_2026-05-03.md.',
  },
  // — § v0.16 active pen-testing (wired) —
  {
    kind: 'sql_injection',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/pen-detectors.ts:96',
    runnerSite: 'packages/cli/src/security/pen-detectors.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V16_PEN_TESTING.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'command_injection',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/pen-detectors.ts:192',
    runnerSite: 'packages/cli/src/security/pen-detectors.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V16_PEN_TESTING.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'path_traversal',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/pen-detectors.ts:241',
    runnerSite: 'packages/cli/src/security/pen-detectors.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V16_PEN_TESTING.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'jwt_weak_alg',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/pen-detectors.ts:284',
    runnerSite: 'packages/cli/src/security/pen-detectors.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V16_PEN_TESTING.md',
    defaultSeverity: 'major',
  },
  // — § v0.7 XSS kinds —
  {
    kind: 'xss_reflected',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/execute.ts:1014',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V07_XSS.md',
    defaultSeverity: 'critical',
    harness: true,
  },
  {
    kind: 'xss_dom',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/execute.ts:688',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V07_XSS.md',
    defaultSeverity: 'critical',
  },
  {
    kind: 'xss_stored',
    status: 'deferred',
    inputSource: 'unknown',
    specReference: 'SPEC_V07_XSS.md',
    note: 'Placeholder; v0.8 deliverable.',
    defaultSeverity: 'critical',
  },
  // — § v0.7 auth-flow kinds (wired) —
  {
    kind: 'auth_session_fixation',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/auth-flow.ts:135',
    runnerSite: 'packages/cli/src/phases/auth-flow.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V07_AUTH_FLOWS.md',
    defaultSeverity: 'critical',
  },
  {
    kind: 'password_reset_token_reuse',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/auth-flow.ts:178',
    runnerSite: 'packages/cli/src/phases/auth-flow.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V07_AUTH_FLOWS.md',
    defaultSeverity: 'major',
  },
  // — § v0.6 performance kinds (wired) —
  {
    kind: 'slow_lcp',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/vitals.ts:26',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'slow_inp',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/vitals.ts:45',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'high_cls',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/vitals.ts:65',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'unbounded_list_render',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'major',
    note: 'Deferred: classifier expects DOM child-count payload that no executor emits; execute.ts does not capture child count after render. Prerequisite: wire DOM child-count capture in execute.ts. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'n_plus_one_api_calls',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/request-hygiene.ts:50',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'request_dedup_missing',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/request-hygiene.ts:114',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'request_cancellation_missing',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/request-hygiene.ts:161',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'main_thread_blocked',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/long-tasks.ts:19',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'oversized_bundle',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'major',
    note: 'Deferred: bundle-probe assumes production-build chunk sizes; bin/up.sh runs Vite dev server whose unminified chunks never exceed threshold. Prerequisite: production build step before probe. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'excessive_re_renders',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V06_PERFORMANCE.md',
    defaultSeverity: 'minor',
    note: 'Deferred: classifier needs React DevTools profiler rerender counts; no production driver populates this field on any run. Prerequisite: React DevTools shim wired into execute. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'memory_leak_suspected',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V08_MEMORY_LEAK.md',
    defaultSeverity: 'major',
    note: 'Deferred: classifier needs sustained-interaction loop traces; default crawler does not produce them and no stress-loop runner exists in execute. Prerequisite: deliberate interaction stress loop. See SWEEP_AUDIT_2026-05-03.md.',
  },
  {
    kind: 'memory_leak_attributed',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V08_MEMORY_LEAK.md',
    defaultSeverity: 'major',
    note: 'Deferred: depends on memory_leak_suspected upstream, which is itself deferred pending stress-loop runner. See SWEEP_AUDIT_2026-05-03.md.',
  },
  // — § v0.6 a11y baseline kinds (wired) —
  {
    kind: 'axe_color_contrast_strong',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/a11y-baseline.ts:58',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'keyboard_trap',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/a11y-baseline.ts:95',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'focus_lost_after_action',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/a11y-baseline.ts:108',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'image_missing_alt',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/a11y-baseline.ts:70',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  {
    kind: 'form_input_unlabeled',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/a11y-baseline.ts:82',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  // — § v0.12 click-evaluate kinds —
  {
    kind: 'interactive_element_missing_accessible_name',
    status: 'wired',
    detectorSite: 'packages/cli/src/phases/execute.ts:848',
    runnerSite: 'packages/cli/src/phases/click-runner.ts',
    inputSource: 'production',
    specReference: 'SPEC_V12_CLICK_ACCESSIBLE_NAME.md',
    defaultSeverity: 'minor',
    harness: true,
    note: 'V56.3 promoted from deferred. Production click-runner emit path requires a11y probe (still gated). Harness provides an independent static-scan path scanning <button>/<a href> for missing accessible name. V33 self-test fixture: a11y-bad/no-name.',
  },
  // — § v0.6 SEO hygiene kinds (wired) —
  {
    kind: 'seo_title_missing',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/seo.ts:60',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  {
    kind: 'seo_title_duplicate_across_routes',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/seo.ts:131',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  {
    kind: 'seo_meta_description_missing',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/seo.ts:69',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  {
    kind: 'seo_canonical_missing',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/seo.ts:78',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  {
    kind: 'seo_h1_missing_or_multiple',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/seo.ts:87',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  {
    kind: 'seo_robots_blocking_crawl',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/seo.ts:100',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V06_A11Y_SEO.md',
    defaultSeverity: 'minor',
    harness: true,
  },
  // — § v0.40 multi-context kinds (wired) —
  {
    kind: 'multi_context_state_divergence',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/multi-context-detectors.ts:49',
    runnerSite: 'packages/cli/src/phases/multi-context-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V40_MULTI_CONTEXT.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'visibility_change_state_loss',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/multi-context-detectors.ts:97',
    runnerSite: 'packages/cli/src/phases/multi-context-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V40_MULTI_CONTEXT.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'multi_user_inconsistent_snapshot',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V40_MULTI_CONTEXT.md',
    defaultSeverity: 'major',
    note: 'Deferred: requires ≥2 simultaneously authenticated sessions; no active fixture configures multi-role auth (idor-bad has roles but auth.kind=none). Prerequisite: surface with real multi-role auth configured. See SWEEP_AUDIT_2026-05-03.md.',
  },
  // — § v0.22 nav-state kinds (wired) —
  {
    kind: 'nav_state_corruption',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/nav-state.ts:68',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V22_NAV_STATE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'nav_resubmit_on_back',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/nav-state.ts:86',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V22_NAV_STATE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'nav_refresh_double_mutation',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/nav-state.ts:51',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V22_NAV_STATE.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'nav_form_state_lost',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/nav-state.ts:222',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V22_NAV_STATE.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'nav_form_state_stale',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/nav-state.ts:233',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V22_NAV_STATE.md',
    defaultSeverity: 'minor',
  },


  // v0.36 browser-platform surface kinds
  {
    kind: 'service_worker_stale',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'SW waiting/installing on second visit; skipWaiting not called.',
    defaultSeverity: 'minor',
  },
  {
    kind: 'web_worker_error',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'Unhandled error/messageerror event on a Web Worker.',
    defaultSeverity: 'major',
  },
  {
    kind: 'iframe_postmessage_unguarded',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'postMessage listener missing event.origin guard.',
    defaultSeverity: 'major',
  },
  {
    kind: 'shadow_dom_a11y_violation',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'axe-core critical/serious violation inside an open shadow root.',
    defaultSeverity: 'major',
  },
  {
    kind: 'permission_denied_unhandled',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V36.x',
    defaultSeverity: 'minor',
  },
  {
    kind: 'webrtc_ice_failure',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'RTCPeerConnection reaches failed/disconnected state without onfailure handler.',
    defaultSeverity: 'major',
  },
  {
    kind: 'subresource_integrity_violation',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'Script/style loaded without integrity= attribute from a cross-origin URL.',
    defaultSeverity: 'major',
  },
  {
    kind: 'coop_coep_violation',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'SharedArrayBuffer used but crossOriginIsolated is false (missing COOP/COEP headers).',
    defaultSeverity: 'major',
  },
  {
    kind: 'trusted_types_violation',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/browser-platform-probe.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V36_BROWSER_PLATFORM.md',
    note: 'Trusted Types CSP violation — unsafe DOM sink usage detected.',
    defaultSeverity: 'major',
  },

  // — § v0.20 network-fault kinds (wired) —
  {
    kind: 'network_fault_unhandled',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/network-fault-unhandled.ts:54',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V20_NETWORK_FAULTS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'network_fault_optimistic_no_revert',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/network-fault-optimistic-revert.ts:51',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V20_NETWORK_FAULTS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'infinite_loading',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V20_NETWORK_FAULTS.md',
    note: 'deferred until runner wired in v0.50 — preHadSpinner/postHasSpinner hardcoded false in execute.ts:1331-1332',
    defaultSeverity: 'major',
  },

  // — § v0.43 agentic-app detection kinds —
  {
    kind: 'agent_response_hallucinated',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V43_AGENTIC_DETECTION.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V43.x',
    defaultSeverity: 'major',
  },
  {
    kind: 'agent_action_timeout',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V43_AGENTIC_DETECTION.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V43.x',
    defaultSeverity: 'major',
  },
  {
    kind: 'prompt_injection_executed',
    status: 'wired',
    detectorSite: 'packages/cli/src/security/pen-detectors.ts',
    runnerSite: 'packages/cli/src/security/pen-test-runner.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V43_AGENTIC_DETECTION.md',
    defaultSeverity: 'critical',
  },
  {
    kind: 'streaming_response_truncated',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V43_AGENTIC_DETECTION.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V43.x',
    defaultSeverity: 'minor',
  },
  {
    kind: 'tool_call_failure_unhandled',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V43_AGENTIC_DETECTION.md',
    note: 'deferred until runner wired in v0.50 — no production caller in execute.ts despite detectorSite claim — V43.x',
    defaultSeverity: 'major',
  },
  {
    kind: 'agent_cost_per_turn_high',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V43_AGENTIC_DETECTION.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V43.x',
    defaultSeverity: 'info',
  },

  // — § v0.37 i18n / locale stress kinds (wired) —
  {
    kind: 'i18n_rtl_layout_break',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/locale/rtl.ts:33',
    runnerSite: 'packages/cli/src/phases/locale-stress.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V37_I18N_STRESS.md',
    defaultSeverity: 'major',
  },
  {
    kind: 'i18n_long_string_overflow',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/locale/long-string.ts:42',
    runnerSite: 'packages/cli/src/phases/locale-stress.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V37_I18N_STRESS.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'i18n_date_format_ambiguous',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/locale/ambiguous-date.ts:40',
    runnerSite: 'packages/cli/src/phases/locale-stress.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V37_I18N_STRESS.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'i18n_hardcoded_string',
    status: 'wired',
    detectorSite: 'packages/cli/src/static/tools/hardcoded-strings.ts:138',
    inputSource: 'production',
    specReference: 'SPEC_V37_I18N_STRESS.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'i18n_pluralization_broken',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/locale/pluralization.ts:41',
    runnerSite: 'packages/cli/src/phases/locale-stress.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V37_I18N_STRESS.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'i18n_currency_format_broken',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/locale/currency.ts:44',
    runnerSite: 'packages/cli/src/phases/locale-stress.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V37_I18N_STRESS.md',
    defaultSeverity: 'minor',
  },
  {
    kind: 'i18n_timezone_display_wrong',
    status: 'wired',
    detectorSite: 'packages/cli/src/discovery/locale/timezone-display.ts:43',
    runnerSite: 'packages/cli/src/phases/locale-stress.ts',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V37_I18N_STRESS.md',
    defaultSeverity: 'minor',
  },

  // — § v0.38 interaction-palette kinds (deferred — runner integration pending — V38.x) —
  {
    kind: 'drag_drop_failure',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'major',
  },
  {
    kind: 'paste_handler_failure',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'minor',
  },
  {
    kind: 'autofill_state_desync',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'minor',
  },
  {
    kind: 'animation_state_corruption',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'minor',
  },
  {
    kind: 'print_stylesheet_broken',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'info',
  },
  {
    kind: 'reduced_motion_violation',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'minor',
  },
  {
    kind: 'forced_colors_failure',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'minor',
  },
  {
    kind: 'dark_mode_layout_break',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'minor',
  },
  {
    kind: 'zoom_layout_break',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V38_INTERACTION_PALETTE.md',
    note: 'deferred until runner wired in v0.50',
    defaultSeverity: 'minor',
  },

  // — § v0.42 data-integrity invariant kinds (wired) —
  {
    kind: 'data_integrity_orphan',
    status: 'wired',
    detectorSite: 'packages/cli/src/dataIntegrity/evaluator.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V42_DATA_INTEGRITY.md',
    note: 'Orphaned records detected after mutation (e.g. child records with deleted parent).',
    defaultSeverity: 'major',
  },
  {
    kind: 'money_math_precision',
    status: 'wired',
    detectorSite: 'packages/cli/src/dataIntegrity/evaluator.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V42_DATA_INTEGRITY.md',
    note: 'Floating-point precision loss in monetary calculation.',
    defaultSeverity: 'critical',
  },
  {
    kind: 'cache_staleness',
    status: 'wired',
    detectorSite: 'packages/cli/src/dataIntegrity/evaluator.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V42_DATA_INTEGRITY.md',
    note: 'Cached value diverges from source-of-truth after mutation.',
    defaultSeverity: 'minor',
  },
  {
    kind: 'idempotency_key_violation',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V42_DATA_INTEGRITY.md',
    note: 'deferred until runner wired in v0.50 — replay clause requires idempotencyKey header on actionResult; no fixture currently supplies it',
    defaultSeverity: 'major',
  },
  {
    kind: 'audit_log_missing_for_mutation',
    status: 'wired',
    detectorSite: 'packages/cli/src/dataIntegrity/evaluator.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V42_DATA_INTEGRITY.md',
    note: 'Mutating action produced no audit log entry.',
    defaultSeverity: 'major',
  },
  {
    kind: 'soft_delete_consistency',
    status: 'wired',
    detectorSite: 'packages/cli/src/dataIntegrity/evaluator.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V42_DATA_INTEGRITY.md',
    note: 'Soft-deleted record still visible via read query.',
    defaultSeverity: 'major',
  },

  // — § v0.41 mobile / responsive kinds (wired) —
  {
    kind: 'touch_target_too_small',
    status: 'wired',
    detectorSite: 'packages/cli/src/classify/a11y-baseline.ts',
    runnerSite: 'packages/cli/src/phases/execute.ts',
    inputSource: 'production',
    specReference: 'SPEC_V41_MOBILE_RESPONSIVE.md',
    note: 'Interactive element bounding rect below 44×44 CSS px on mobile viewport.',
    defaultSeverity: 'minor',
  },
  {
    kind: 'hover_only_affordance',
    status: 'wired',
    detectorSite: 'packages/cli/src/static/tools/hover-only-affordance.ts',
    inputSource: 'production',
    specReference: 'SPEC_V41_MOBILE_RESPONSIVE.md',
    note: 'CSS :hover-only interactive affordance with no touch/focus equivalent.',
    defaultSeverity: 'minor',
  },
  {
    kind: 'viewport_100vh_break',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V41_MOBILE_RESPONSIVE.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V41.x',
    defaultSeverity: 'minor',
  },
  {
    kind: 'soft_keyboard_occlusion',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V41_MOBILE_RESPONSIVE.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V41.x',
    defaultSeverity: 'minor',
  },
  {
    kind: 'orientation_change_layout_break',
    status: 'deferred',
    inputSource: 'synthetic-only',
    specReference: 'SPEC_V41_MOBILE_RESPONSIVE.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V41.x',
    defaultSeverity: 'minor',
  },
  {
    kind: 'pull_to_refresh_conflict',
    status: 'deferred',
    inputSource: 'production',
    specReference: 'SPEC_V41_MOBILE_RESPONSIVE.md',
    note: 'deferred until runner wired in v0.50 — runner integration pending — V41.x',
    defaultSeverity: 'minor',
  },
];

/**
 * Compile-time exhaustiveness: any BugKind not in DETECTOR_REGISTRY produces a
 * type error here. New BugKinds added to types.ts MUST add a registry entry.
 */
type _ExhaustivenessCheck = Exclude<BugKind, (typeof DETECTOR_REGISTRY)[number]['kind']> extends never
  ? true
  : ['DETECTOR_REGISTRY missing entries for BugKinds:', Exclude<BugKind, (typeof DETECTOR_REGISTRY)[number]['kind']>];

export function lookupDetector(kind: BugKind): DetectorRegistryEntry | undefined {
  return DETECTOR_REGISTRY.find(e => e.kind === kind);
}

// v0.29: severity / CWE / exploitability metadata for export emitters.
import type { ExploitabilityModel } from '../types.js';

export type DetectorMetadata = {
  kind: BugKind;
  severity: Severity;
  cwe?: string[];
  exploitabilityModel?: ExploitabilityModel;
  helpUri?: string;
  displayName: string;
  description: string;
};

/**
 * v0.29: Record-keyed view of DETECTOR_REGISTRY for O(1) lookups by kind.
 * Provides DetectorMetadata shape; severity is taken from the registry's
 * per-kind defaultSeverity (calibrated in v0.29 fix for #147).
 */
export const DETECTOR_REGISTRY_MAP: Record<string, DetectorMetadata | undefined> = Object.fromEntries(
  DETECTOR_REGISTRY.map(e => [e.kind, {
    kind: e.kind,
    severity: e.defaultSeverity ?? 'info',
    displayName: e.kind,
    description: e.note ?? '',
  } satisfies DetectorMetadata]),
);
