// auth-safe.ts — GENERATED by hardcoded-creds-mini/bin/up.sh. DO NOT COMMIT.
// Negative case: loads the Stripe key from the environment, not hardcoded.
// gitleaks should produce zero findings for this file.

const stripeKey = process.env.STRIPE_KEY;

export { stripeKey };
