// auth-comment.ts — GENERATED by hardcoded-creds-mini/bin/up.sh. DO NOT COMMIT.
// Edge case: the Stripe key appears only in a source comment, not in executable code.
// gitleaks scans comments as part of the source text — this should STILL fire.

// example: @@STRIPE_KEY@@

export {};
