// auth.ts — GENERATED by hardcoded-creds-mini/bin/up.sh. DO NOT COMMIT.
// This file contains intentionally planted credentials for gitleaks fixture testing.

// P1: Stripe secret key (canonical gitleaks fixture string)
const STRIPE_KEY = "@@STRIPE_KEY@@";

// P2: AWS access key (canonical gitleaks fixture string)
const AWS_ACCESS_KEY = "@@AWS_ACCESS_KEY@@";

export { STRIPE_KEY, AWS_ACCESS_KEY };
